services:

  csv-import-app:
    image: "kaymakcisw/csv-import-app"
    container_name: csv-import-app-ms
    depends_on:
      postgresdb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "csv-import-app"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/tedtalks"
      POSTGRES_PASSWORD: root
    networks:
      - csv-import

  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d tedtalks" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: tedtalks
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - csv-import

volumes:
  postgres_data:

networks:
  csv-import:
    driver: "bridge"